---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---
```{r message=FALSE, warning=FALSE}
library(readxl)
library(mosaic)
library(tidyverse)
library(tibble)
library(matrixStats)
Shipments <- read_excel("Shipments.xls", col_names = FALSE)
NewOrders <- read_excel("NewOrders.xls", col_names = FALSE)
UnfilledOrders <- read_excel("UnfilledOrders.xls", col_names = FALSE)
TotalInventories <- read_excel("TotalInventories.xls", col_names = FALSE)
InventoriesToShipments <- read_excel("InventoriesToShipments.xls", col_names = FALSE)
UnfilledOrdersToShipments <- read_excel("UnfilledOrdersToShipments.xls", col_names = FALSE)
```
```{r}
shipments_industry_code_list <- as.array(unique(Shipments$...1))
shipments_dataframe <- tibble(.rows = 360)
```

```{r message=FALSE, warning=FALSE}
for (i in 1:length(shipments_industry_code_list))
{
  current_code <- shipments_industry_code_list[i]
  current_industry <- Shipments %>% filter(Shipments$...1 == current_code, Shipments$...2 != "2022") %>% select(3:14)
  current_industry_transpose <- as.list(t(current_industry))
  for (j in 1:length(current_industry_transpose))
  {
    shipments_dataframe[j,i] = current_industry_transpose[j]
  }
  shipments_dataframe[i] <- sapply(shipments_dataframe[i],as.numeric)
}
colnames(shipments_dataframe) = shipments_industry_code_list
dates <- seq(from = as.Date("1992/01/01"), to = as.Date("2021/12/01"), by = "months")
dates2 <- format(dates, "%m/%y")
shipments_dataframe_time <- shipments_dataframe %>% add_column(Date = dates2)
head(shipments_dataframe_time,12)
```
```{r}
neworders_industry_code_list <- as.array(unique(NewOrders$...1))
neworders_dataframe <- tibble(.rows = 360)
```
```{r message=FALSE, warning=FALSE}
for (i in 1:length(neworders_industry_code_list))
{
  current_code <- neworders_industry_code_list[i]
  current_industry <- NewOrders %>% filter(NewOrders$...1 == current_code, NewOrders$...2 != "2022") %>% select(3:14)
  current_industry_transpose <- as.list(t(current_industry))
  for (j in 1:length(current_industry_transpose))
  {
    neworders_dataframe[j,i] = current_industry_transpose[j]
  }
  neworders_dataframe[i] <- sapply(neworders_dataframe[i],as.numeric)
}
colnames(neworders_dataframe) = neworders_industry_code_list
dates <- seq(from = as.Date("1992/01/01"), to = as.Date("2021/12/01"), by = "months")
dates2 <- format(dates, "%m/%y")
neworders_dataframe_time <- neworders_dataframe %>% add_column(Date = dates2)
head(neworders_dataframe_time,12)
```
```{r}
unfilledorders_industry_code_list <- as.array(unique(UnfilledOrders$...1))
unfilledorders_dataframe <- tibble(.rows = 360)
```
```{r message=FALSE, warning=FALSE}
for (i in 1:length(unfilledorders_industry_code_list))
{
  current_code <- unfilledorders_industry_code_list[i]
  current_industry <- UnfilledOrders %>% filter(UnfilledOrders$...1 == current_code, UnfilledOrders$...2 != "2022") %>% select(3:14)
  current_industry_transpose <- as.list(t(current_industry))
  for (j in 1:length(current_industry_transpose))
  {
    unfilledorders_dataframe[j,i] = current_industry_transpose[j]
  }
  unfilledorders_dataframe[i] <- sapply(unfilledorders_dataframe[i],as.numeric)
}
colnames(unfilledorders_dataframe) = unfilledorders_industry_code_list
dates <- seq(from = as.Date("1992/01/01"), to = as.Date("2021/12/01"), by = "months")
dates2 <- format(dates, "%m/%y")
unfilledorders_dataframe_time <- unfilledorders_dataframe %>% add_column(Date = dates2)
head(unfilledorders_dataframe_time,12)
```
```{r}
totalinventories_industry_code_list <- as.array(unique(TotalInventories$...1))
totalinventories_dataframe <- tibble(.rows = 360)
```
```{r message=FALSE, warning=FALSE}
for (i in 1:length(totalinventories_industry_code_list))
{
  current_code <- totalinventories_industry_code_list[i]
  current_industry <- TotalInventories %>% filter(TotalInventories$...1 == current_code, TotalInventories$...2 != "2022") %>% select(3:14)
  current_industry_transpose <- as.list(t(current_industry))
  for (j in 1:length(current_industry_transpose))
  {
    totalinventories_dataframe[j,i] = current_industry_transpose[j]
  }
  totalinventories_dataframe[i] <- sapply(totalinventories_dataframe[i],as.numeric)
}
colnames(totalinventories_dataframe) = totalinventories_industry_code_list
dates <- seq(from = as.Date("1992/01/01"), to = as.Date("2021/12/01"), by = "months")
dates2 <- format(dates, "%m/%y")
totalinventories_dataframe_time <- totalinventories_dataframe %>% add_column(Date = dates2)
head(totalinventories_dataframe_time,12)
```
```{r}
inventoriestoshipments_industry_code_list <- as.array(unique(InventoriesToShipments$...1))
inventoriestoshipments_dataframe <- tibble(.rows = 360)
```
```{r message=FALSE, warning=FALSE}
for (i in 1:length(inventoriestoshipments_industry_code_list))
{
  current_code <- inventoriestoshipments_industry_code_list[i]
  current_industry <- InventoriesToShipments %>% filter(InventoriesToShipments$...1 == current_code, InventoriesToShipments$...2 != "2022") %>% select(3:14)
  current_industry_transpose <- as.list(t(current_industry))
  for (j in 1:length(current_industry_transpose))
  {
    inventoriestoshipments_dataframe[j,i] = current_industry_transpose[j]
  }
  inventoriestoshipments_dataframe[i] <- sapply(inventoriestoshipments_dataframe[i],as.numeric)
}
colnames(inventoriestoshipments_dataframe) = inventoriestoshipments_industry_code_list
dates <- seq(from = as.Date("1992/01/01"), to = as.Date("2021/12/01"), by = "months")
dates2 <- format(dates, "%m/%y")
inventoriestoshipments_dataframe_time <- inventoriestoshipments_dataframe %>% add_column(Date = dates2)
head(inventoriestoshipments_dataframe_time,12)
```
```{r}
unfilledorderstoshipments_industry_code_list <- as.array(unique(UnfilledOrdersToShipments$...1))
unfilledorderstoshipments_dataframe <- tibble(.rows = 360)
```
```{r message=FALSE, warning=FALSE}
for (i in 1:length(unfilledorderstoshipments_industry_code_list))
{
  current_code <- unfilledorderstoshipments_industry_code_list[i]
  current_industry <- UnfilledOrdersToShipments %>% filter(UnfilledOrdersToShipments$...1 == current_code, UnfilledOrdersToShipments$...2 != "2022") %>% select(3:14)
  current_industry_transpose <- as.list(t(current_industry))
  for (j in 1:length(current_industry_transpose))
  {
    unfilledorderstoshipments_dataframe[j,i] = current_industry_transpose[j]
  }
  unfilledorderstoshipments_dataframe[i] <- sapply(unfilledorderstoshipments_dataframe[i],as.numeric)
}
colnames(unfilledorderstoshipments_dataframe) = unfilledorderstoshipments_industry_code_list
dates <- seq(from = as.Date("1992/01/01"), to = as.Date("2021/12/01"), by = "months")
dates2 <- format(dates, "%m/%y")
unfilledorderstoshipments_dataframe_time <- unfilledorderstoshipments_dataframe %>% add_column(Date = dates2)
head(unfilledorderstoshipments_dataframe_time,12)
```
```{r}
mean_row_ship <- colMeans(shipments_dataframe_time[sapply(shipments_dataframe_time, is.numeric)],na.rm = TRUE)
median_row_ship <- colMedians(as.matrix(shipments_dataframe_time[sapply(shipments_dataframe_time, is.numeric)]),na.rm = TRUE)
sd_row_ship <- colSds(as.matrix(shipments_dataframe_time[sapply(shipments_dataframe_time, is.numeric)]),na.rm = TRUE)
shipments_mmv1 <- shipments_dataframe_time %>% rbind(shipments_dataframe_time, mean_row_ship)
shipments_mmv2 <- shipments_mmv1 %>% rbind(shipments_mmv1, median_row_ship)
shipments_mmv <- shipments_mmv2 %>% rbind(shipments_mmv2, sd_row_ship)
shipments_mmv[nrow(shipments_mmv)-2,ncol(shipments_mmv)] <- "Mean"
shipments_mmv[nrow(shipments_mmv)-1,ncol(shipments_mmv)] <- "Median"
shipments_mmv[nrow(shipments_mmv),ncol(shipments_mmv)] <- "Standard Deviation"
tail(shipments_mmv,10)
```
```{r}
mean_row_neword <- colMeans(neworders_dataframe_time[sapply(neworders_dataframe_time, is.numeric)],na.rm = TRUE)
median_row_neword <- colMedians(as.matrix(neworders_dataframe_time[sapply(neworders_dataframe_time, is.numeric)]),na.rm = TRUE)
sd_row_neword <- colSds(as.matrix(neworders_dataframe_time[sapply(neworders_dataframe_time, is.numeric)]),na.rm = TRUE)
neworders_mmv1 <- neworders_dataframe_time %>% rbind(neworders_dataframe_time, mean_row_neword)
neworders_mmv2 <- neworders_mmv1 %>% rbind(neworders_mmv1, median_row_neword)
neworders_mmv <- neworders_mmv2 %>% rbind(neworders_mmv2, sd_row_neword)
neworders_mmv[nrow(neworders_mmv)-2,ncol(neworders_mmv)] <- "Mean"
neworders_mmv[nrow(neworders_mmv)-1,ncol(neworders_mmv)] <- "Median"
neworders_mmv[nrow(neworders_mmv),ncol(neworders_mmv)] <- "Standard Deviation"
tail(neworders_mmv,10)
```
```{r}
mean_row_unfillord <- colMeans(unfilledorders_dataframe_time[sapply(unfilledorders_dataframe_time, is.numeric)],na.rm = TRUE)
median_row_unfillord <- colMedians(as.matrix(unfilledorders_dataframe_time[sapply(unfilledorders_dataframe_time, is.numeric)]),na.rm = TRUE)
sd_row_unfillord <- colSds(as.matrix(unfilledorders_dataframe_time[sapply(unfilledorders_dataframe_time, is.numeric)]),na.rm = TRUE)
unfillord_mmv1 <- unfilledorders_dataframe_time %>% rbind(unfilledorders_dataframe_time, mean_row_unfillord)
unfillord_mmv2 <- unfillord_mmv1 %>% rbind(unfillord_mmv1, median_row_unfillord)
unfillord_mmv <- unfillord_mmv2 %>% rbind(unfillord_mmv2, sd_row_unfillord)
unfillord_mmv[nrow(unfillord_mmv)-2,ncol(unfillord_mmv)] <- "Mean"
unfillord_mmv[nrow(unfillord_mmv)-1,ncol(unfillord_mmv)] <- "Median"
unfillord_mmv[nrow(unfillord_mmv),ncol(unfillord_mmv)] <- "Standard Deviation"
tail(unfillord_mmv,10)
```
```{r}
mean_row_totalinv <- colMeans(totalinventories_dataframe_time[sapply(totalinventories_dataframe_time, is.numeric)],na.rm = TRUE)
median_row_totalinv <- colMedians(as.matrix(totalinventories_dataframe_time[sapply(totalinventories_dataframe_time, is.numeric)]),na.rm = TRUE)
sd_row_totalinv <- colSds(as.matrix(totalinventories_dataframe_time[sapply(totalinventories_dataframe_time, is.numeric)]),na.rm = TRUE)
totalinv_mmv1 <- totalinventories_dataframe_time %>% rbind(totalinventories_dataframe_time, mean_row_totalinv)
totalinv_mmv2 <- totalinv_mmv1 %>% rbind(totalinv_mmv1, median_row_totalinv)
totalinv_mmv <- totalinv_mmv2 %>% rbind(totalinv_mmv2, sd_row_totalinv)
totalinv_mmv[nrow(totalinv_mmv)-2,ncol(totalinv_mmv)] <- "Mean"
totalinv_mmv[nrow(totalinv_mmv)-1,ncol(totalinv_mmv)] <- "Median"
totalinv_mmv[nrow(totalinv_mmv),ncol(totalinv_mmv)] <- "Standard Deviation"
tail(totalinv_mmv,10)
```
```{r}
mean_row_invtoship <- colMeans(inventoriestoshipments_dataframe_time[sapply(inventoriestoshipments_dataframe_time, is.numeric)],na.rm = TRUE)
median_row_invtoship <- colMedians(as.matrix(inventoriestoshipments_dataframe_time[sapply(inventoriestoshipments_dataframe_time, is.numeric)]),na.rm = TRUE)
sd_row_invtoship <- colSds(as.matrix(inventoriestoshipments_dataframe_time[sapply(inventoriestoshipments_dataframe_time, is.numeric)]),na.rm = TRUE)
invtoship_mmv1 <- inventoriestoshipments_dataframe_time %>% rbind(inventoriestoshipments_dataframe_time, mean_row_invtoship)
invtoship_mmv2 <- invtoship_mmv1 %>% rbind(invtoship_mmv1, median_row_invtoship)
invtoship_mmv <- invtoship_mmv2 %>% rbind(invtoship_mmv2, sd_row_invtoship)
invtoship_mmv[nrow(invtoship_mmv)-2,ncol(invtoship_mmv)] <- "Mean"
invtoship_mmv[nrow(invtoship_mmv)-1,ncol(invtoship_mmv)] <- "Median"
invtoship_mmv[nrow(invtoship_mmv),ncol(invtoship_mmv)] <- "Standard Deviation"
tail(invtoship_mmv,10)
```
```{r}
mean_row_unfilltoship <- colMeans(unfilledorderstoshipments_dataframe_time[sapply(unfilledorderstoshipments_dataframe_time, is.numeric)],na.rm = TRUE)
median_row_unfilltoship <- colMedians(as.matrix(unfilledorderstoshipments_dataframe_time[sapply(unfilledorderstoshipments_dataframe_time, is.numeric)]),na.rm = TRUE)
sd_row_unfilltoship <- colSds(as.matrix(unfilledorderstoshipments_dataframe_time[sapply(unfilledorderstoshipments_dataframe_time, is.numeric)]),na.rm = TRUE)
unfilltoship_mmv1 <- unfilledorderstoshipments_dataframe_time %>% rbind(unfilledorderstoshipments_dataframe_time, mean_row_unfilltoship)
unfilltoship_mmv2 <- unfilltoship_mmv1 %>% rbind(unfilltoship_mmv1, median_row_unfilltoship)
unfilltoship_mmv <- unfilltoship_mmv2 %>% rbind(unfilltoship_mmv2, sd_row_unfilltoship)
unfilltoship_mmv[nrow(unfilltoship_mmv)-2,ncol(unfilltoship_mmv)] <- "Mean"
unfilltoship_mmv[nrow(unfilltoship_mmv)-1,ncol(unfilltoship_mmv)] <- "Median"
unfilltoship_mmv[nrow(unfilltoship_mmv),ncol(unfilltoship_mmv)] <- "Standard Deviation"
tail(unfilltoship_mmv,10)
```
```{r}
shipment_means <- shipments_mmv %>% filter(shipments_mmv$Date == "Mean") %>% select_if(. >= 300000)
shipment_means
```
```{r}
AMTMVS <- ts(data = shipments_mmv$AMTMVS, start=c(1992), end=c(2021), frequency = 12)
AMXTVS <- ts(data = shipments_mmv$AMXTVS, start=c(1992), end=c(2021), frequency = 12)
AMXDVS <- ts(data = shipments_mmv$AMXDVS, start=c(1992), end=c(2021), frequency = 12)
ts.plot(AMTMVS, AMXTVS, AMXDVS, gpars=list(xlab="Year", ylab="Value",lty=c(1:3)), col=rep(c("red","blue","green")))
legend("topleft", legend = c("AMTMVS","AMXTVS","AMXDVS"), col = c("red","blue","green"), lty=c(1:3))
```
```{r}
shipments_order <- order(colMeans(shipments_dataframe_time[sapply(shipments_dataframe_time, is.numeric)],na.rm = TRUE))
shipments_mmv_ordered_mean <- shipments_mmv %>% select(all_of(shipments_order), ncol(shipments_mmv))
shipments_mmv_ordered_mean_adj <- shipments_mmv_ordered_mean %>% select(starts_with('A')) #87 Columns
shipments_mmv_ordered_mean_unadj <- shipments_mmv_ordered_mean %>% select(starts_with('U')) #87 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81))
{
  Series1 <- ts(data = shipments_mmv_ordered_mean_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = shipments_mmv_ordered_mean_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = shipments_mmv_ordered_mean_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = shipments_mmv_ordered_mean_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = shipments_mmv_ordered_mean_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(shipments_mmv_ordered_mean_adj)[i],colnames(shipments_mmv_ordered_mean_adj)[i+1],colnames(shipments_mmv_ordered_mean_adj)[i+2],colnames(shipments_mmv_ordered_mean_adj)[i+3],colnames(shipments_mmv_ordered_mean_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81))
{
  Series1 <- ts(data = shipments_mmv_ordered_mean_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = shipments_mmv_ordered_mean_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = shipments_mmv_ordered_mean_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = shipments_mmv_ordered_mean_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = shipments_mmv_ordered_mean_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(shipments_mmv_ordered_mean_unadj)[i],colnames(shipments_mmv_ordered_mean_unadj)[i+1],colnames(shipments_mmv_ordered_mean_unadj)[i+2],colnames(shipments_mmv_ordered_mean_unadj)[i+3],colnames(shipments_mmv_ordered_mean_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```

```{r}
neworders_order <- order(colMeans(neworders_dataframe_time[sapply(neworders_dataframe_time, is.numeric)],na.rm = TRUE))
neworders_mmv_ordered_mean <- neworders_mmv %>% select(all_of(neworders_order), ncol(neworders_mmv))
neworders_mmv_ordered_mean_adj <- neworders_mmv_ordered_mean %>% select(starts_with('A')) #52 Columns
neworders_mmv_ordered_mean_unadj <- neworders_mmv_ordered_mean %>% select(starts_with('U')) #52 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = neworders_mmv_ordered_mean_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = neworders_mmv_ordered_mean_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = neworders_mmv_ordered_mean_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = neworders_mmv_ordered_mean_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = neworders_mmv_ordered_mean_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(neworders_mmv_ordered_mean_adj)[i],colnames(neworders_mmv_ordered_mean_adj)[i+1],colnames(neworders_mmv_ordered_mean_adj)[i+2],colnames(neworders_mmv_ordered_mean_adj)[i+3],colnames(neworders_mmv_ordered_mean_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = neworders_mmv_ordered_mean_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = neworders_mmv_ordered_mean_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = neworders_mmv_ordered_mean_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = neworders_mmv_ordered_mean_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = neworders_mmv_ordered_mean_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(neworders_mmv_ordered_mean_unadj)[i],colnames(neworders_mmv_ordered_mean_unadj)[i+1],colnames(neworders_mmv_ordered_mean_unadj)[i+2],colnames(neworders_mmv_ordered_mean_unadj)[i+3],colnames(neworders_mmv_ordered_mean_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```

```{r}
unfilledorders_order <- order(colMeans(unfilledorders_dataframe_time[sapply(unfilledorders_dataframe_time, is.numeric)],na.rm = TRUE))
unfilledorders_mmv_ordered_mean <- unfillord_mmv %>% select(all_of(unfilledorders_order), ncol(unfillord_mmv))
unfilledorders_mmv_ordered_mean_adj <- unfilledorders_mmv_ordered_mean %>% select(starts_with('A')) #50 Columns
unfilledorders_mmv_ordered_mean_unadj <- unfilledorders_mmv_ordered_mean %>% select(starts_with('U')) #52 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = unfilledorders_mmv_ordered_mean_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilledorders_mmv_ordered_mean_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilledorders_mmv_ordered_mean_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilledorders_mmv_ordered_mean_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilledorders_mmv_ordered_mean_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilledorders_mmv_ordered_mean_adj)[i],colnames(unfilledorders_mmv_ordered_mean_adj)[i+1],colnames(unfilledorders_mmv_ordered_mean_adj)[i+2],colnames(unfilledorders_mmv_ordered_mean_adj)[i+3],colnames(unfilledorders_mmv_ordered_mean_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = unfilledorders_mmv_ordered_mean_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilledorders_mmv_ordered_mean_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilledorders_mmv_ordered_mean_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilledorders_mmv_ordered_mean_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilledorders_mmv_ordered_mean_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilledorders_mmv_ordered_mean_unadj)[i],colnames(unfilledorders_mmv_ordered_mean_unadj)[i+1],colnames(unfilledorders_mmv_ordered_mean_unadj)[i+2],colnames(unfilledorders_mmv_ordered_mean_unadj)[i+3],colnames(unfilledorders_mmv_ordered_mean_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```

```{r}
totalinv_order <- order(colMeans(totalinventories_dataframe_time[sapply(totalinventories_dataframe_time, is.numeric)],na.rm = TRUE))
totalinv_mmv_ordered_mean <- totalinv_mmv %>% select(all_of(totalinv_order), ncol(totalinv_mmv))
totalinv_mmv_ordered_mean_adj <- totalinv_mmv_ordered_mean %>% select(starts_with('A')) #158 Columns
totalinv_mmv_ordered_mean_unadj <- totalinv_mmv_ordered_mean %>% select(starts_with('U')) #158 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151))
{
  Series1 <- ts(data = totalinv_mmv_ordered_mean_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = totalinv_mmv_ordered_mean_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = totalinv_mmv_ordered_mean_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = totalinv_mmv_ordered_mean_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = totalinv_mmv_ordered_mean_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(totalinv_mmv_ordered_mean_adj)[i],colnames(totalinv_mmv_ordered_mean_adj)[i+1],colnames(totalinv_mmv_ordered_mean_adj)[i+2],colnames(totalinv_mmv_ordered_mean_adj)[i+3],colnames(totalinv_mmv_ordered_mean_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151))
{
  Series1 <- ts(data = totalinv_mmv_ordered_mean_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = totalinv_mmv_ordered_mean_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = totalinv_mmv_ordered_mean_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = totalinv_mmv_ordered_mean_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = totalinv_mmv_ordered_mean_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(totalinv_mmv_ordered_mean_unadj)[i],colnames(totalinv_mmv_ordered_mean_unadj)[i+1],colnames(totalinv_mmv_ordered_mean_unadj)[i+2],colnames(totalinv_mmv_ordered_mean_unadj)[i+3],colnames(totalinv_mmv_ordered_mean_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```

```{r}
invtoship_order <- order(colMeans(inventoriestoshipments_dataframe_time[sapply(inventoriestoshipments_dataframe_time, is.numeric)],na.rm = TRUE))
invtoship_mmv_ordered_mean <- invtoship_mmv %>% select(all_of(invtoship_order), ncol(invtoship_mmv))
invtoship_mmv_ordered_mean_adj <- invtoship_mmv_ordered_mean %>% select(starts_with('A')) #24 Columns
invtoship_mmv_ordered_mean_unadj <- invtoship_mmv_ordered_mean %>% select(starts_with('U')) #24 Columns
for (i in c(1,6,11,16))
{
  Series1 <- ts(data = invtoship_mmv_ordered_mean_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = invtoship_mmv_ordered_mean_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = invtoship_mmv_ordered_mean_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = invtoship_mmv_ordered_mean_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = invtoship_mmv_ordered_mean_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(invtoship_mmv_ordered_mean_adj)[i],colnames(invtoship_mmv_ordered_mean_adj)[i+1],colnames(invtoship_mmv_ordered_mean_adj)[i+2],colnames(invtoship_mmv_ordered_mean_adj)[i+3],colnames(invtoship_mmv_ordered_mean_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16))
{
  Series1 <- ts(data = invtoship_mmv_ordered_mean_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = invtoship_mmv_ordered_mean_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = invtoship_mmv_ordered_mean_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = invtoship_mmv_ordered_mean_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = invtoship_mmv_ordered_mean_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(invtoship_mmv_ordered_mean_unadj)[i],colnames(invtoship_mmv_ordered_mean_unadj)[i+1],colnames(invtoship_mmv_ordered_mean_unadj)[i+2],colnames(invtoship_mmv_ordered_mean_unadj)[i+3],colnames(invtoship_mmv_ordered_mean_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```

```{r}
unfilltoship_order <- order(colMeans(unfilledorderstoshipments_dataframe_time[sapply(unfilledorderstoshipments_dataframe_time, is.numeric)],na.rm = TRUE))
unfilltoship_mmv_ordered_mean <- unfilltoship_mmv %>% select(all_of(unfilltoship_order), ncol(unfilltoship_mmv))
unfilltoship_mmv_ordered_mean_adj <- unfilltoship_mmv_ordered_mean %>% select(starts_with('A')) #9 Columns
unfilltoship_mmv_ordered_mean_unadj <- unfilltoship_mmv_ordered_mean %>% select(starts_with('U')) #9 Columns
for (i in c(1))
{
  Series1 <- ts(data = unfilltoship_mmv_ordered_mean_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilltoship_mmv_ordered_mean_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilltoship_mmv_ordered_mean_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilltoship_mmv_ordered_mean_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilltoship_mmv_ordered_mean_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilltoship_mmv_ordered_mean_adj)[i],colnames(unfilltoship_mmv_ordered_mean_adj)[i+1],colnames(unfilltoship_mmv_ordered_mean_adj)[i+2],colnames(unfilltoship_mmv_ordered_mean_adj)[i+3],colnames(unfilltoship_mmv_ordered_mean_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1))
{
  Series1 <- ts(data = unfilltoship_mmv_ordered_mean_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilltoship_mmv_ordered_mean_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilltoship_mmv_ordered_mean_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilltoship_mmv_ordered_mean_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilltoship_mmv_ordered_mean_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilltoship_mmv_ordered_mean_unadj)[i],colnames(unfilltoship_mmv_ordered_mean_unadj)[i+1],colnames(unfilltoship_mmv_ordered_mean_unadj)[i+2],colnames(unfilltoship_mmv_ordered_mean_unadj)[i+3],colnames(unfilltoship_mmv_ordered_mean_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
shipments_order_med <- order(colMedians(as.matrix(shipments_dataframe_time[sapply(shipments_dataframe_time, is.numeric)]),na.rm = TRUE))
shipments_mmv_ordered_median <- shipments_mmv %>% select(all_of(shipments_order_med), ncol(shipments_mmv))
shipments_mmv_ordered_median_adj <- shipments_mmv_ordered_median %>% select(starts_with('A')) #87 Columns
shipments_mmv_ordered_median_unadj <- shipments_mmv_ordered_median %>% select(starts_with('U')) #87 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81))
{
  Series1 <- ts(data = shipments_mmv_ordered_median_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = shipments_mmv_ordered_median_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = shipments_mmv_ordered_median_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = shipments_mmv_ordered_median_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = shipments_mmv_ordered_median_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(shipments_mmv_ordered_median_adj)[i],colnames(shipments_mmv_ordered_median_adj)[i+1],colnames(shipments_mmv_ordered_median_adj)[i+2],colnames(shipments_mmv_ordered_median_adj)[i+3],colnames(shipments_mmv_ordered_median_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81))
{
  Series1 <- ts(data = shipments_mmv_ordered_median_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = shipments_mmv_ordered_median_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = shipments_mmv_ordered_median_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = shipments_mmv_ordered_median_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = shipments_mmv_ordered_median_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(shipments_mmv_ordered_median_unadj)[i],colnames(shipments_mmv_ordered_median_unadj)[i+1],colnames(shipments_mmv_ordered_median_unadj)[i+2],colnames(shipments_mmv_ordered_median_unadj)[i+3],colnames(shipments_mmv_ordered_median_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
neworders_order_med <- order(colMeans(as.matrix(neworders_dataframe_time[sapply(neworders_dataframe_time, is.numeric)]),na.rm = TRUE))
neworders_mmv_ordered_median <- neworders_mmv %>% select(all_of(neworders_order_med), ncol(neworders_mmv))
neworders_mmv_ordered_median_adj <- neworders_mmv_ordered_median %>% select(starts_with('A')) #52 Columns
neworders_mmv_ordered_median_unadj <- neworders_mmv_ordered_median %>% select(starts_with('U')) #52 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = neworders_mmv_ordered_median_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = neworders_mmv_ordered_median_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = neworders_mmv_ordered_median_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = neworders_mmv_ordered_median_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = neworders_mmv_ordered_median_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(neworders_mmv_ordered_median_adj)[i],colnames(neworders_mmv_ordered_median_adj)[i+1],colnames(neworders_mmv_ordered_median_adj)[i+2],colnames(neworders_mmv_ordered_median_adj)[i+3],colnames(neworders_mmv_ordered_median_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = neworders_mmv_ordered_median_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = neworders_mmv_ordered_median_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = neworders_mmv_ordered_median_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = neworders_mmv_ordered_median_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = neworders_mmv_ordered_median_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(neworders_mmv_ordered_median_unadj)[i],colnames(neworders_mmv_ordered_median_unadj)[i+1],colnames(neworders_mmv_ordered_median_unadj)[i+2],colnames(neworders_mmv_ordered_median_unadj)[i+3],colnames(neworders_mmv_ordered_median_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
unfilledorders_order_med <- order(colMedians(as.matrix(unfilledorders_dataframe_time[sapply(unfilledorders_dataframe_time, is.numeric)]),na.rm = TRUE))
unfilledorders_mmv_ordered_median <- unfillord_mmv %>% select(all_of(unfilledorders_order_med), ncol(unfillord_mmv))
unfilledorders_mmv_ordered_median_adj <- unfilledorders_mmv_ordered_median %>% select(starts_with('A')) #50 Columns
unfilledorders_mmv_ordered_median_unadj <- unfilledorders_mmv_ordered_median %>% select(starts_with('U')) #52 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = unfilledorders_mmv_ordered_median_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilledorders_mmv_ordered_median_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilledorders_mmv_ordered_median_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilledorders_mmv_ordered_median_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilledorders_mmv_ordered_median_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilledorders_mmv_ordered_median_adj)[i],colnames(unfilledorders_mmv_ordered_median_adj)[i+1],colnames(unfilledorders_mmv_ordered_median_adj)[i+2],colnames(unfilledorders_mmv_ordered_median_adj)[i+3],colnames(unfilledorders_mmv_ordered_median_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = unfilledorders_mmv_ordered_median_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilledorders_mmv_ordered_median_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilledorders_mmv_ordered_median_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilledorders_mmv_ordered_median_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilledorders_mmv_ordered_median_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilledorders_mmv_ordered_median_unadj)[i],colnames(unfilledorders_mmv_ordered_median_unadj)[i+1],colnames(unfilledorders_mmv_ordered_median_unadj)[i+2],colnames(unfilledorders_mmv_ordered_median_unadj)[i+3],colnames(unfilledorders_mmv_ordered_median_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
totalinv_order_med <- order(colMedians(as.matrix(totalinventories_dataframe_time[sapply(totalinventories_dataframe_time, is.numeric)]),na.rm = TRUE))
totalinv_mmv_ordered_median <- totalinv_mmv %>% select(all_of(totalinv_order_med), ncol(totalinv_mmv))
totalinv_mmv_ordered_median_adj <- totalinv_mmv_ordered_median %>% select(starts_with('A')) #158 Columns
totalinv_mmv_ordered_median_unadj <- totalinv_mmv_ordered_median %>% select(starts_with('U')) #158 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151))
{
  Series1 <- ts(data = totalinv_mmv_ordered_median_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = totalinv_mmv_ordered_median_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = totalinv_mmv_ordered_median_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = totalinv_mmv_ordered_median_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = totalinv_mmv_ordered_median_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(totalinv_mmv_ordered_median_adj)[i],colnames(totalinv_mmv_ordered_median_adj)[i+1],colnames(totalinv_mmv_ordered_median_adj)[i+2],colnames(totalinv_mmv_ordered_median_adj)[i+3],colnames(totalinv_mmv_ordered_median_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151))
{
  Series1 <- ts(data = totalinv_mmv_ordered_median_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = totalinv_mmv_ordered_median_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = totalinv_mmv_ordered_median_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = totalinv_mmv_ordered_median_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = totalinv_mmv_ordered_median_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(totalinv_mmv_ordered_median_unadj)[i],colnames(totalinv_mmv_ordered_median_unadj)[i+1],colnames(totalinv_mmv_ordered_median_unadj)[i+2],colnames(totalinv_mmv_ordered_median_unadj)[i+3],colnames(totalinv_mmv_ordered_median_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
invtoship_order_med <- order(colMedians(as.matrix(inventoriestoshipments_dataframe_time[sapply(inventoriestoshipments_dataframe_time, is.numeric)]),na.rm = TRUE))
invtoship_mmv_ordered_median <- invtoship_mmv %>% select(all_of(invtoship_order_med), ncol(invtoship_mmv))
invtoship_mmv_ordered_median_adj <- invtoship_mmv_ordered_median %>% select(starts_with('A')) #24 Columns
invtoship_mmv_ordered_median_unadj <- invtoship_mmv_ordered_median %>% select(starts_with('U')) #24 Columns
for (i in c(1,6,11,16))
{
  Series1 <- ts(data = invtoship_mmv_ordered_median_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = invtoship_mmv_ordered_median_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = invtoship_mmv_ordered_median_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = invtoship_mmv_ordered_median_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = invtoship_mmv_ordered_median_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(invtoship_mmv_ordered_median_adj)[i],colnames(invtoship_mmv_ordered_median_adj)[i+1],colnames(invtoship_mmv_ordered_median_adj)[i+2],colnames(invtoship_mmv_ordered_median_adj)[i+3],colnames(invtoship_mmv_ordered_median_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16))
{
  Series1 <- ts(data = invtoship_mmv_ordered_median_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = invtoship_mmv_ordered_median_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = invtoship_mmv_ordered_median_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = invtoship_mmv_ordered_median_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = invtoship_mmv_ordered_median_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(invtoship_mmv_ordered_median_unadj)[i],colnames(invtoship_mmv_ordered_median_unadj)[i+1],colnames(invtoship_mmv_ordered_median_unadj)[i+2],colnames(invtoship_mmv_ordered_median_unadj)[i+3],colnames(invtoship_mmv_ordered_median_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
unfilltoship_order_med <- order(colMedians(as.matrix(unfilledorderstoshipments_dataframe_time[sapply(unfilledorderstoshipments_dataframe_time, is.numeric)]),na.rm = TRUE))
unfilltoship_mmv_ordered_median <- unfilltoship_mmv %>% select(all_of(unfilltoship_order_med), ncol(unfilltoship_mmv))
unfilltoship_mmv_ordered_median_adj <- unfilltoship_mmv_ordered_median %>% select(starts_with('A')) #9 Columns
unfilltoship_mmv_ordered_median_unadj <- unfilltoship_mmv_ordered_median %>% select(starts_with('U')) #9 Columns
for (i in c(1))
{
  Series1 <- ts(data = unfilltoship_mmv_ordered_median_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilltoship_mmv_ordered_median_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilltoship_mmv_ordered_median_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilltoship_mmv_ordered_median_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilltoship_mmv_ordered_median_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilltoship_mmv_ordered_median_adj)[i],colnames(unfilltoship_mmv_ordered_median_adj)[i+1],colnames(unfilltoship_mmv_ordered_median_adj)[i+2],colnames(unfilltoship_mmv_ordered_median_adj)[i+3],colnames(unfilltoship_mmv_ordered_median_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1))
{
  Series1 <- ts(data = unfilltoship_mmv_ordered_median_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilltoship_mmv_ordered_median_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilltoship_mmv_ordered_median_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilltoship_mmv_ordered_median_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilltoship_mmv_ordered_median_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilltoship_mmv_ordered_median_unadj)[i],colnames(unfilltoship_mmv_ordered_median_unadj)[i+1],colnames(unfilltoship_mmv_ordered_median_unadj)[i+2],colnames(unfilltoship_mmv_ordered_median_unadj)[i+3],colnames(unfilltoship_mmv_ordered_median_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
shipments_order_sd <- order(colSds(as.matrix(shipments_dataframe_time[sapply(shipments_dataframe_time, is.numeric)]),na.rm = TRUE))
shipments_mmv_ordered_standev <- shipments_mmv %>% select(all_of(shipments_order_sd), ncol(shipments_mmv))
shipments_mmv_ordered_standev_adj <- shipments_mmv_ordered_standev %>% select(starts_with('A')) #9 Columns
shipments_mmv_ordered_standev_unadj <- shipments_mmv_ordered_standev %>% select(starts_with('U')) #9 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81))
{
  Series1 <- ts(data = shipments_mmv_ordered_standev_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = shipments_mmv_ordered_standev_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = shipments_mmv_ordered_standev_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = shipments_mmv_ordered_standev_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = shipments_mmv_ordered_standev_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(shipments_mmv_ordered_standev_adj)[i],colnames(shipments_mmv_ordered_standev_adj)[i+1],colnames(shipments_mmv_ordered_standev_adj)[i+2],colnames(shipments_mmv_ordered_standev_adj)[i+3],colnames(shipments_mmv_ordered_standev_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81))
{
  Series1 <- ts(data = shipments_mmv_ordered_standev_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = shipments_mmv_ordered_standev_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = shipments_mmv_ordered_standev_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = shipments_mmv_ordered_standev_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = shipments_mmv_ordered_standev_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(shipments_mmv_ordered_standev_unadj)[i],colnames(shipments_mmv_ordered_standev_unadj)[i+1],colnames(shipments_mmv_ordered_standev_unadj)[i+2],colnames(shipments_mmv_ordered_standev_unadj)[i+3],colnames(shipments_mmv_ordered_standev_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
neworders_order_sd <- order(colSds(as.matrix(neworders_dataframe_time[sapply(neworders_dataframe_time, is.numeric)]),na.rm = TRUE))
neworders_mmv_ordered_standev <- neworders_mmv %>% select(all_of(neworders_order_sd), ncol(neworders_mmv))
neworders_mmv_ordered_standev_adj <- neworders_mmv_ordered_standev %>% select(starts_with('A')) #52 Columns
neworders_mmv_ordered_standev_unadj <- neworders_mmv_ordered_standev %>% select(starts_with('U')) #52 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = neworders_mmv_ordered_standev_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = neworders_mmv_ordered_standev_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = neworders_mmv_ordered_standev_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = neworders_mmv_ordered_standev_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = neworders_mmv_ordered_standev_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(neworders_mmv_ordered_standev_adj)[i],colnames(neworders_mmv_ordered_standev_adj)[i+1],colnames(neworders_mmv_ordered_standev_adj)[i+2],colnames(neworders_mmv_ordered_standev_adj)[i+3],colnames(neworders_mmv_ordered_standev_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = neworders_mmv_ordered_standev_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = neworders_mmv_ordered_standev_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = neworders_mmv_ordered_standev_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = neworders_mmv_ordered_standev_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = neworders_mmv_ordered_standev_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(neworders_mmv_ordered_standev_unadj)[i],colnames(neworders_mmv_ordered_standev_unadj)[i+1],colnames(neworders_mmv_ordered_standev_unadj)[i+2],colnames(neworders_mmv_ordered_standev_unadj)[i+3],colnames(neworders_mmv_ordered_standev_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
unfilledorders_order_sd <- order(colSds(as.matrix(unfilledorders_dataframe_time[sapply(unfilledorders_dataframe_time, is.numeric)]),na.rm = TRUE))
unfilledorders_mmv_ordered_standev <- unfillord_mmv %>% select(all_of(unfilledorders_order_sd), ncol(unfillord_mmv))
unfilledorders_mmv_ordered_standev_adj <- unfilledorders_mmv_ordered_standev %>% select(starts_with('A')) #50 Columns
unfilledorders_mmv_ordered_standev_unadj <- unfilledorders_mmv_ordered_standev %>% select(starts_with('U')) #52 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = unfilledorders_mmv_ordered_standev_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilledorders_mmv_ordered_standev_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilledorders_mmv_ordered_standev_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilledorders_mmv_ordered_standev_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilledorders_mmv_ordered_standev_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilledorders_mmv_ordered_standev_adj)[i],colnames(unfilledorders_mmv_ordered_standev_adj)[i+1],colnames(unfilledorders_mmv_ordered_standev_adj)[i+2],colnames(unfilledorders_mmv_ordered_standev_adj)[i+3],colnames(unfilledorders_mmv_ordered_standev_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46))
{
  Series1 <- ts(data = unfilledorders_mmv_ordered_standev_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilledorders_mmv_ordered_standev_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilledorders_mmv_ordered_standev_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilledorders_mmv_ordered_standev_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilledorders_mmv_ordered_standev_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilledorders_mmv_ordered_standev_unadj)[i],colnames(unfilledorders_mmv_ordered_standev_unadj)[i+1],colnames(unfilledorders_mmv_ordered_standev_unadj)[i+2],colnames(unfilledorders_mmv_ordered_standev_unadj)[i+3],colnames(unfilledorders_mmv_ordered_standev_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
totalinv_order_sd <- order(colSds(as.matrix(totalinventories_dataframe_time[sapply(totalinventories_dataframe_time, is.numeric)]),na.rm = TRUE))
totalinv_mmv_ordered_standev <- totalinv_mmv %>% select(all_of(totalinv_order_sd), ncol(totalinv_mmv))
totalinv_mmv_ordered_standev_adj <- totalinv_mmv_ordered_standev %>% select(starts_with('A')) #158 Columns
totalinv_mmv_ordered_standev_unadj <- totalinv_mmv_ordered_standev %>% select(starts_with('U')) #158 Columns
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151))
{
  Series1 <- ts(data = totalinv_mmv_ordered_standev_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = totalinv_mmv_ordered_standev_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = totalinv_mmv_ordered_standev_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = totalinv_mmv_ordered_standev_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = totalinv_mmv_ordered_standev_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(totalinv_mmv_ordered_standev_adj)[i],colnames(totalinv_mmv_ordered_standev_adj)[i+1],colnames(totalinv_mmv_ordered_standev_adj)[i+2],colnames(totalinv_mmv_ordered_standev_adj)[i+3],colnames(totalinv_mmv_ordered_standev_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16,21,26,31,36,41,46,51,56,61,66,71,76,81,86,91,96,101,106,111,116,121,126,131,136,141,146,151))
{
  Series1 <- ts(data = totalinv_mmv_ordered_standev_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = totalinv_mmv_ordered_standev_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = totalinv_mmv_ordered_standev_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = totalinv_mmv_ordered_standev_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = totalinv_mmv_ordered_standev_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(totalinv_mmv_ordered_standev_unadj)[i],colnames(totalinv_mmv_ordered_standev_unadj)[i+1],colnames(totalinv_mmv_ordered_standev_unadj)[i+2],colnames(totalinv_mmv_ordered_standev_unadj)[i+3],colnames(totalinv_mmv_ordered_standev_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
invtoship_order_sd <- order(colSds(as.matrix(inventoriestoshipments_dataframe_time[sapply(inventoriestoshipments_dataframe_time, is.numeric)]),na.rm = TRUE))
invtoship_mmv_ordered_standev <- invtoship_mmv %>% select(all_of(invtoship_order_sd), ncol(invtoship_mmv))
invtoship_mmv_ordered_standev_adj <- invtoship_mmv_ordered_standev %>% select(starts_with('A')) #24 Columns
invtoship_mmv_ordered_standev_unadj <- invtoship_mmv_ordered_standev %>% select(starts_with('U')) #24 Columns
for (i in c(1,6,11,16))
{
  Series1 <- ts(data = invtoship_mmv_ordered_standev_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = invtoship_mmv_ordered_standev_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = invtoship_mmv_ordered_standev_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = invtoship_mmv_ordered_standev_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = invtoship_mmv_ordered_standev_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(invtoship_mmv_ordered_standev_adj)[i],colnames(invtoship_mmv_ordered_standev_adj)[i+1],colnames(invtoship_mmv_ordered_standev_adj)[i+2],colnames(invtoship_mmv_ordered_standev_adj)[i+3],colnames(invtoship_mmv_ordered_standev_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1,6,11,16))
{
  Series1 <- ts(data = invtoship_mmv_ordered_standev_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = invtoship_mmv_ordered_standev_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = invtoship_mmv_ordered_standev_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = invtoship_mmv_ordered_standev_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = invtoship_mmv_ordered_standev_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(invtoship_mmv_ordered_standev_unadj)[i],colnames(invtoship_mmv_ordered_standev_unadj)[i+1],colnames(invtoship_mmv_ordered_standev_unadj)[i+2],colnames(invtoship_mmv_ordered_standev_unadj)[i+3],colnames(invtoship_mmv_ordered_standev_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
unfilltoship_order_sd <- order(colSds(as.matrix(unfilledorderstoshipments_dataframe_time[sapply(unfilledorderstoshipments_dataframe_time, is.numeric)]),na.rm = TRUE))
unfilltoship_mmv_ordered_standev <- unfilltoship_mmv %>% select(all_of(unfilltoship_order_sd), ncol(unfilltoship_mmv))
unfilltoship_mmv_ordered_standev_adj <- unfilltoship_mmv_ordered_standev %>% select(starts_with('A')) #9 Columns
unfilltoship_mmv_ordered_standev_unadj <- unfilltoship_mmv_ordered_standev %>% select(starts_with('U')) #9 Columns
for (i in c(1))
{
  Series1 <- ts(data = unfilltoship_mmv_ordered_standev_adj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilltoship_mmv_ordered_standev_adj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilltoship_mmv_ordered_standev_adj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilltoship_mmv_ordered_standev_adj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilltoship_mmv_ordered_standev_adj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilltoship_mmv_ordered_standev_adj)[i],colnames(unfilltoship_mmv_ordered_standev_adj)[i+1],colnames(unfilltoship_mmv_ordered_standev_adj)[i+2],colnames(unfilltoship_mmv_ordered_standev_adj)[i+3],colnames(unfilltoship_mmv_ordered_standev_adj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```
```{r}
for (i in c(1))
{
  Series1 <- ts(data = unfilltoship_mmv_ordered_standev_unadj[,i], start=c(1992), end=c(2021), frequency = 12)
  Series2 <- ts(data = unfilltoship_mmv_ordered_standev_unadj[,i+1], start=c(1992), end=c(2021), frequency = 12)
  Series3 <- ts(data = unfilltoship_mmv_ordered_standev_unadj[,i+2], start=c(1992), end=c(2021), frequency = 12)
  Series4 <- ts(data = unfilltoship_mmv_ordered_standev_unadj[,i+3], start=c(1992), end=c(2021), frequency = 12)
  Series5 <- ts(data = unfilltoship_mmv_ordered_standev_unadj[,i+4], start=c(1992), end=c(2021), frequency = 12)
  ts.plot(Series1, Series2, Series3, Series4, Series5, gpars=list(xlab="Year", ylab="Value",lty=c(1:5)), col=rep(c("red","purple","black","green","blue")))
  legend("topleft", legend = c(colnames(unfilltoship_mmv_ordered_standev_unadj)[i],colnames(unfilltoship_mmv_ordered_standev_unadj)[i+1],colnames(unfilltoship_mmv_ordered_standev_unadj)[i+2],colnames(unfilltoship_mmv_ordered_standev_unadj)[i+3],colnames(unfilltoship_mmv_ordered_standev_unadj)[i+4]), col = c("red","purple","black","green","blue"), lty=c(1:4))
}
```


